"""Adiciona created_at à Task com nullable

Revision ID: 9bf4a0d494d1
Revises: 58ee7727c274
Create Date: 2025-05-24 19:25:20.074040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf4a0d494d1'
down_revision = '58ee7727c274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
